bookers/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.
  root :to  => "homes#top"
  post "books" => "books#create"
  get "books" => "books#index"
  get "books/:id" => "books#show",as:"book"
  get "books/:id/edit" => "books#edit",as:"edit_book"
  patch "books/:id" => "books#update",as:"update_book"
  delete "books/:id" => "books#destroy",as:"destroy_book"
end

bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers/app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all.order(id: :asc)
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      render("books/index")
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render("books/edit")
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      flash[:notice] = "Book was successfully destroyed."
      redirect_to books_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/helpers/homes_helper.rb
module HomesHelper
end

bookers/app/views/books/edit.html.erb
<body>
    <h1>Editing Book</h1>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
      <% @book.errors.full_messages.each do |message| %>
      <ul><li><%= message %></li></ul>
      <% end %>
    </div>
  <% end %>
  
<%= form_with model:@book, url: update_book_path(@book.id), local:true do |f| %>
<div class="field">
<label for="book_title">Title</label>
  <%= f.text_field :title %>
</div>

<div class="field">
  <label for="book_body">Body</label>
  <%= f.text_area :body %>
</div>

<div class="actions">
  <%= f.submit "Update Book" %>
</div>
<% end %>

<%= link_to "Show",book_path(@book.id) %>
 |
<a class="back" href="/books">Back</a>



</body>

bookers/app/views/books/index.html.erb
<body>
    <p id="notice"></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

    <tbody>
  <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show",book_path(book.id) %></td>
        <td><%= link_to "Edit",edit_book_path(book.id) %></td>
        <td><%= link_to "Destroy",destroy_book_path(book.id), method: :delete,"data-confirm" => "Are you sure?" %></td>
      </tr>
  <% end %>
    </tbody>
</table>


<h2>New book</h2>
<% if @book.errors.any? %>
 <div id="error_explanation">
　<h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
  <% @book.errors.full_messages.each do |message| %>
    <ul><li><%= message %></li></ul>
  <% end %>
 </div>
<% end %>
<%= form_with model:@book, url:"/books" ,local:true do |f| %>
<div class="field">
  <label for="book_title">Title</label>
  <%= f.text_field :title %>
</div>

<div class="field">
  <label for="book_body">Body</label>
  <%= f.text_area :body %>
</div>

<div class="actions">
  <%= f.submit "Create Book" %>
</div>
<% end %>
</body>

bookers/app/views/books/show.html.erb
<body>
    <p id="notice"></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

<%= link_to "Edit",edit_book_path(@book.id) %>
 |
<a class="back" href="/books">Back</a>



</body>

bookers/app/views/homes/top.html.erb
<body>
    <h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<p><a href="/books">start</a></p>    	
  

</body>

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
     <div class ="flash">
       <%= flash[:notice] %>
     </div>
    <% end %>
    <%= yield %>
  </body>
</html>